<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBuN7n0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBuN7n0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBuN7n0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBuN7n0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOBuN7n0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OBuN7n0',
    'container.build_id' => 'ef9833f3',
    'container.build_time' => 1615722187,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBuN7n0');
