<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'wines' => [[], ['_controller' => 'App\\Controller\\DefaultController::wines'], [], [['text', '/']], [], []],
    'wine' => [['slug'], ['_controller' => 'App\\Controller\\DefaultController::wine'], [], [['variable', '/', '[^/]++', 'slug'], ['text', '/our-wines']], [], []],
    'app_helloworld_sayhello' => [[], ['_controller' => 'App\\Controller\\HelloWorldController::sayHello'], [], [['text', '/hello-world']], [], []],
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
];
